// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrJsZus4m4zRCWZ3K2Aq84-OMCZeSWo2o',
    appId: '1:891008958889:web:406d73c020e21b8f1004b8',
    messagingSenderId: '891008958889',
    projectId: 'iot-2026-tharuka',
    authDomain: 'iot-2026-tharuka.firebaseapp.com',
    databaseURL: 'https://iot-2026-tharuka-default-rtdb.firebaseio.com',
    storageBucket: 'iot-2026-tharuka.firebasestorage.app',
    measurementId: 'G-3VX43KX3FB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAO348XpRIIAn9TJIjvA7mOOmxnwBbvWPg',
    appId: '1:891008958889:android:bcd30333598cf16e1004b8',
    messagingSenderId: '891008958889',
    projectId: 'iot-2026-tharuka',
    databaseURL: 'https://iot-2026-tharuka-default-rtdb.firebaseio.com',
    storageBucket: 'iot-2026-tharuka.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaW_sUTZycEIYeW-AK6hO6ITBJQhWyrN8',
    appId: '1:891008958889:ios:d409b56bf9b563131004b8',
    messagingSenderId: '891008958889',
    projectId: 'iot-2026-tharuka',
    databaseURL: 'https://iot-2026-tharuka-default-rtdb.firebaseio.com',
    storageBucket: 'iot-2026-tharuka.firebasestorage.app',
    iosBundleId: 'com.example.iot2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaW_sUTZycEIYeW-AK6hO6ITBJQhWyrN8',
    appId: '1:891008958889:ios:d409b56bf9b563131004b8',
    messagingSenderId: '891008958889',
    projectId: 'iot-2026-tharuka',
    databaseURL: 'https://iot-2026-tharuka-default-rtdb.firebaseio.com',
    storageBucket: 'iot-2026-tharuka.firebasestorage.app',
    iosBundleId: 'com.example.iot2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrJsZus4m4zRCWZ3K2Aq84-OMCZeSWo2o',
    appId: '1:891008958889:web:4dae83e3f7f64c6b1004b8',
    messagingSenderId: '891008958889',
    projectId: 'iot-2026-tharuka',
    authDomain: 'iot-2026-tharuka.firebaseapp.com',
    databaseURL: 'https://iot-2026-tharuka-default-rtdb.firebaseio.com',
    storageBucket: 'iot-2026-tharuka.firebasestorage.app',
    measurementId: 'G-D476ZNJE7F',
  );
}
